language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: RCFIlRe9LT1Rr6OeTSVWrBzz/v2+vZjuL92GRZWy/Vd1bC04/7P6RYAKL7zhqR/oWSnJgfkAzp0wNPIC28qJeqtC9Px6/9WygujxcoGv3CtpYxvwKbW30dXgyM/gnC+AZTRSQ2G3S+SoBFDxTGaF2ykfCWsFZHL2qlIviIXU58GGsWK3ufCWdt/7lY3pabWhV7mqJc6onru5oBGp/iyEBmi29/aRIV4+h8N9GY17uPHikPkPrnsytzIRPR9q/RSPfu+m93KQTOC5gpKm1mvoUsz91jYLV+iarxJBjt0Xd9Mtnt4auYfS6AlyebS6GzIhh+8eZymzvUpusL0PV0XI0snsUNfIiolxpmfh7ruXuVQ5jWv468BJc8qQvl4CHHIS1x9rJ6pZowaRDVSdIdPzCrbRkLBT1PI49U016eKEA4SUtR/R4NAI/UoJjfwSkw8PFXQ/ia9Yc+uZSpQNV/iCaHkNbwdTfPzo9UWGzLtPM9IAY/SMiURBXlpMD6Ptgy8TLebXU3lU90/xGAhTjAUsseesxbBfIO+gr2KhSMscLT9RQBnWio3I90UjUDosrRXXXZabGTS6wKGxnTGLxMnulmsfJYXrDyaRb0rSxXWE0KdVqACBftq8udH/4D030iKNaXBMPWXHUd/pFjyugmqtv8C42l8X64iGoV4E2BrS2/Y=
  app: fierce-cliffs-97625
  on:
    repo: sanadler/mytube-client
